package animalid

import (
	"math/rand"
	"strings"
)

var (
	adjective = [...]string{
		"admiring",
		"adoring",
		"affectionate",
		"agitated",
		"amazing",
		"angry",
		"awesome",
		"blissful",
		"boring",
		"brave",
		"clever",
		"cocky",
		"compassionate",
		"competent",
		"condescending",
		"confident",
		"cranky",
		"dazzling",
		"determined",
		"distracted",
		"dreamy",
		"eager",
		"ecstatic",
		"elastic",
		"elated",
		"elegant",
		"eloquent",
		"epic",
		"fervent",
		"festive",
		"flamboyant",
		"focused",
		"friendly",
		"frosty",
		"gallant",
		"gifted",
		"goofy",
		"gracious",
		"happy",
		"hardcore",
		"heuristic",
		"hopeful",
		"hungry",
		"infallible",
		"inspiring",
		"jolly",
		"jovial",
		"keen",
		"kind",
		"laughing",
		"loving",
		"lucid",
		"mystifying",
		"modest",
		"musing",
		"naughty",
		"nervous",
		"nifty",
		"nostalgic",
		"objective",
		"optimistic",
		"peaceful",
		"pedantic",
		"pensive",
		"practical",
		"priceless",
		"quirky",
		"quizzical",
		"relaxed",
		"reverent",
		"romantic",
		"sad",
		"serene",
		"sharp",
		"silly",
		"sleepy",
		"stoic",
		"stupefied",
		"suspicious",
		"tender",
		"thirsty",
		"trusting",
		"unruffled",
		"upbeat",
		"vibrant",
		"vigilant",
		"vigorous",
		"wizardly",
		"wonderful",
		"xenodochial",
		"youthful",
		"zealous",
		"zen",
	}
	animal = [...]string{
		"aardvark",
		"albatross",
		"alligator",
		"alpaca",
		"ant",
		"anteater",
		"antelope",
		"ape",
		"armadillo",
		"donkey",
		"baboon",
		"badger",
		"barracuda",
		"bat",
		"bear",
		"beaver",
		"bee",
		"bison",
		"boar",
		"buffalo",
		"butterfly",
		"camel",
		"capybara",
		"caribou",
		"cassowary",
		"cat",
		"caterpillar",
		"cattle",
		"chamois",
		"cheetah",
		"chicken",
		"chimpanzee",
		"chinchilla",
		"chough",
		"clam",
		"cobra",
		"cockroach",
		"cod",
		"cormorant",
		"coyote",
		"crab",
		"crane",
		"crocodile",
		"crow",
		"curlew",
		"deer",
		"dinosaur",
		"dog",
		"dogfish",
		"dolphin",
		"dotterel",
		"dove",
		"dragonfly",
		"duck",
		"dugong",
		"dunlin",
		"eagle",
		"echidna",
		"eel",
		"eland",
		"elephant",
		"elk",
		"emu",
		"falcon",
		"ferret",
		"finch",
		"fish",
		"flamingo",
		"fly",
		"fox",
		"frog",
		"gaur",
		"gazelle",
		"gerbil",
		"giraffe",
		"gnat",
		"gnu",
		"goat",
		"goldfinch",
		"goldfish",
		"goose",
		"gorilla",
		"goshawk",
		"grasshopper",
		"grouse",
		"guanaco",
		"gull",
		"hamster",
		"hare",
		"hawk",
		"hedgehog",
		"heron",
		"herring",
		"hippopotamus",
		"hornet",
		"horse",
		"human",
		"hummingbird",
		"hyena",
		"ibex",
		"ibis",
		"jackal",
		"jaguar",
		"jay",
		"jellyfish",
		"kangaroo",
		"kingfisher",
		"koala",
		"kookabura",
		"kouprey",
		"kudu",
		"lapwing",
		"lark",
		"lemur",
		"leopard",
		"lion",
		"llama",
		"lobster",
		"locust",
		"loris",
		"louse",
		"lyrebird",
		"magpie",
		"mallard",
		"manatee",
		"mandrill",
		"mantis",
		"marten",
		"meerkat",
		"mink",
		"mole",
		"mongoose",
		"monkey",
		"moose",
		"mosquito",
		"mouse",
		"mule",
		"narwhal",
		"newt",
		"nightingale",
		"octopus",
		"okapi",
		"opossum",
		"oryx",
		"ostrich",
		"otter",
		"owl",
		"oyster",
		"panther",
		"parrot",
		"partridge",
		"peafowl",
		"pelican",
		"penguin",
		"pheasant",
		"pig",
		"pigeon",
		"pony",
		"porcupine",
		"porpoise",
		"quail",
		"quelea",
		"quetzal",
		"rabbit",
		"raccoon",
		"rail",
		"ram",
		"rat",
		"raven",
		"red deer",
		"red panda",
		"reindeer",
		"rhinoceros",
		"rook",
		"salamander",
		"salmon",
		"sand dollar",
		"sandpiper",
		"sardine",
		"scorpion",
		"seahorse",
		"seal",
		"shark",
		"sheep",
		"shrew",
		"skunk",
		"snail",
		"snake",
		"sparrow",
		"spider",
		"spoonbill",
		"squid",
		"squirrel",
		"starling",
		"stingray",
		"stinkbug",
		"stork",
		"swallow",
		"swan",
		"tapir",
		"tarsier",
		"termite",
		"tiger",
		"toad",
		"trout",
		"turkey",
		"turtle",
		"viper",
		"vulture",
		"wallaby",
		"walrus",
		"wasp",
		"weasel",
		"whale",
		"wildcat",
		"wolf",
		"wolverine",
		"wombat",
		"woodcock",
		"woodpecker",
		"worm",
		"wren",
		"yak",
		"zebra",
	}
)

// GetAnimalID returns an [adjective]-[adjective]-[animal] string
func GetAnimalID() string {

	a, b, c := getRandIndices()
	name := strings.Title(adjective[a]) + strings.Title(adjective[b]) + strings.Title(animal[c])
	return name
}

// GetDelimitedAnimalID returns an [adjective][adjective][animal] string with a delimiter, or title cased if delimiter is empty
func GetDelimitedAnimalID(delimiter string) string {

	a, b, c := getRandIndices()
	// An empty delimiter will trigger Title case for readability
	if delimiter == "" {
		return GetAnimalID()
	}
	name := adjective[a] + delimiter + adjective[b] + delimiter + animal[c]
	return name
}

func getRandIndices() (a, b, c int) {
gen:
	a = rand.Intn(len(adjective))
	b = rand.Intn(len(adjective))
	c = rand.Intn(len(animal))

	if a == b {
		goto gen
	}

	return
}
